import * as path from 'path';
import * as os from 'os';
import * as fs from 'fs';
import type { IdeId, IdeStatus, AiFiles } from '@airtable-formula/shared';
import { getSettings } from '../settings.js';
import { IDE_CONFIGS } from './ide-configs.js';
import { detectInstalledIdes, isIdeInstalled, readConfigFile, writeConfigAtomic, mergeServerEntry, removeServerEntry } from './ide-detection.js';

const MCP_SERVER_NAME = 'airtable-user-mcp';

/** Stable directory for the launcher — never includes a version number. */
const LAUNCHER_DIR = path.join(os.homedir(), '.airtable-user-mcp');
const LAUNCHER_SCRIPT = path.join(LAUNCHER_DIR, 'start.mjs');
const LAUNCHER_CONFIG = path.join(LAUNCHER_DIR, 'bundled-path.json');

/** Launcher script content — a tiny resolver that reads the real path at startup. */
const LAUNCHER_SOURCE = `\
// Auto-generated by the Airtable Formula VS Code extension.
// This file provides a stable path for MCP configs so they survive extension updates.
// Do not edit — it is regenerated on every extension activation.
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __dir = dirname(fileURLToPath(import.meta.url));
const config = JSON.parse(readFileSync(join(__dir, 'bundled-path.json'), 'utf8'));

// Ensure vendored dependencies (patchright, otpauth) are resolvable
if (config.nodePath) process.env.NODE_PATH = config.nodePath;

// Forward CLI args so subcommands (login, status, doctor) still work
const serverUrl = pathToFileURL(config.serverPath).href;
await import(serverUrl);
`;

/**
 * Write (or update) the stable launcher at ~/.airtable-user-mcp/.
 * Call this on every extension activation so bundled-path.json stays current.
 */
export async function ensureLauncher(serverPath: string): Promise<void> {
  const nodeModulesPath = path.resolve(path.dirname(serverPath), '..', 'node_modules');

  await fs.promises.mkdir(LAUNCHER_DIR, { recursive: true });

  // Always update bundled-path.json to point to the current extension version
  await fs.promises.writeFile(
    LAUNCHER_CONFIG,
    JSON.stringify({ serverPath, nodePath: nodeModulesPath }, null, 2) + '\n',
    'utf8',
  );

  // Write the launcher script (idempotent — content is static)
  await fs.promises.writeFile(LAUNCHER_SCRIPT, LAUNCHER_SOURCE, 'utf8');
}

export function buildServerEntry(_serverPath: string): Record<string, unknown> {
  const env: Record<string, string> = {
    AIRTABLE_HEADLESS_ONLY: '1',
    AIRTABLE_PROFILE_DIR: path.join(os.homedir(), '.airtable-user-mcp', '.chrome-profile'),
  };

  const settings = getSettings();
  const choice = settings.auth.browserChoice;
  if (choice?.channel) env.AIRTABLE_BROWSER_CHANNEL = choice.channel;
  if (choice?.executablePath) env.AIRTABLE_BROWSER_PATH = choice.executablePath;

  return {
    command: 'node',
    args: [LAUNCHER_SCRIPT],
    env,
  };
}

export function buildNpxServerEntry(): Record<string, unknown> {
  const env: Record<string, string> = {
    AIRTABLE_HEADLESS_ONLY: '1',
    AIRTABLE_PROFILE_DIR: path.join(os.homedir(), '.airtable-user-mcp', '.chrome-profile'),
  };

  const settings = getSettings();
  const choice = settings.auth.browserChoice;
  if (choice?.channel) env.AIRTABLE_BROWSER_CHANNEL = choice.channel;
  if (choice?.executablePath) env.AIRTABLE_BROWSER_PATH = choice.executablePath;

  return {
    command: 'npx',
    args: ['-y', 'airtable-user-mcp'],
    env,
  };
}

export async function configureMcpForIde(ideId: IdeId, serverPath: string, serverEntry?: Record<string, unknown>): Promise<void> {
  const cfg = IDE_CONFIGS[ideId];
  const existing = await readConfigFile(cfg.mcpConfigPath);
  const entry = serverEntry ?? buildServerEntry(serverPath);
  const merged = mergeServerEntry(existing, cfg.mcpServersKey, MCP_SERVER_NAME, entry);
  await writeConfigAtomic(cfg.mcpConfigPath, merged);
}

export async function unconfigureMcpForIde(ideId: IdeId): Promise<void> {
  const cfg = IDE_CONFIGS[ideId];
  const existing = await readConfigFile(cfg.mcpConfigPath);
  const cleaned = removeServerEntry(existing, cfg.mcpServersKey, MCP_SERVER_NAME);
  await writeConfigAtomic(cfg.mcpConfigPath, cleaned);
}

export async function isMcpConfigured(ideId: IdeId): Promise<boolean> {
  try {
    const cfg = IDE_CONFIGS[ideId];
    const existing = await readConfigFile(cfg.mcpConfigPath);
    const parts = cfg.mcpServersKey.split('.');
    let cur: unknown = existing;
    for (const p of parts) {
      if (typeof cur !== 'object' || cur === null) return false;
      cur = (cur as Record<string, unknown>)[p];
    }
    return typeof cur === 'object' && cur !== null && MCP_SERVER_NAME in (cur as object);
  } catch { return false; }
}

export async function getMcpHealth(ideId: IdeId): Promise<{ configured: boolean; healthy: boolean }> {
  try {
    const cfg = IDE_CONFIGS[ideId];
    const existing = await readConfigFile(cfg.mcpConfigPath);
    const parts = cfg.mcpServersKey.split('.');
    let cur: unknown = existing;
    for (const p of parts) {
      if (typeof cur !== 'object' || cur === null) return { configured: false, healthy: false };
      cur = (cur as Record<string, unknown>)[p];
    }
    if (typeof cur !== 'object' || cur === null || !(MCP_SERVER_NAME in (cur as object))) {
      return { configured: false, healthy: false };
    }
    const entry = (cur as Record<string, unknown>)[MCP_SERVER_NAME] as Record<string, unknown>;
    if (entry.command === 'npx') return { configured: true, healthy: true };
    const args = entry.args as string[] | undefined;
    if (args && args.length > 0) {
      const target = args[0];
      // Launcher path is healthy if the launcher AND its config exist
      if (target === LAUNCHER_SCRIPT) {
        try {
          await fs.promises.access(LAUNCHER_SCRIPT);
          await fs.promises.access(LAUNCHER_CONFIG);
          return { configured: true, healthy: true };
        } catch {
          return { configured: true, healthy: false };
        }
      }
      // Direct path (legacy or override) — check the file itself
      try {
        await fs.promises.access(target);
        return { configured: true, healthy: true };
      } catch {
        return { configured: true, healthy: false };
      }
    }
    return { configured: true, healthy: true };
  } catch { return { configured: false, healthy: false }; }
}

function emptyAiFiles(): AiFiles {
  return { skills: 'missing', rules: 'missing', workflows: 'missing', agents: 'missing' };
}

export async function getIdeStatus(ideId: IdeId): Promise<IdeStatus> {
  const cfg = IDE_CONFIGS[ideId];
  const detected = await isIdeInstalled(ideId);
  const health = detected ? await getMcpHealth(ideId) : { configured: false, healthy: false };
  return {
    ideId,
    label: cfg.label,
    detected,
    mcpConfigured: health.configured,
    mcpServerHealthy: health.configured ? health.healthy : undefined,
    aiFiles: emptyAiFiles(),
  };
}

export async function getAllIdeStatuses(): Promise<IdeStatus[]> {
  const ids = Object.keys(IDE_CONFIGS) as IdeId[];
  return Promise.all(ids.map(getIdeStatus));
}

export { detectInstalledIdes, isIdeInstalled, readConfigFile, writeConfigAtomic, mergeServerEntry, removeServerEntry } from './ide-detection.js';
export { IDE_CONFIGS } from './ide-configs.js';
export type { IdeConfig } from './ide-configs.js';
