import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';
import type { IdeId } from '@airtable-formula/shared';
import { IDE_CONFIGS } from './ide-configs.js';
import { readConfigFile, writeConfigAtomic } from './ide-detection.js';

const LSP_SERVER_KEY = 'airtable-lsp';
const LSP_NPX_CMD   = 'npx';
const LSP_NPX_ARGS  = ['-y', 'airtable-user-lsp', '--stdio'];

// ── Zed: JSON merge into settings.json ─────────────────────────────────────

async function configureZed(configPath: string): Promise<void> {
  const existing = await readConfigFile(configPath);
  const lsp = (existing['lsp'] ?? {}) as Record<string, unknown>;
  lsp[LSP_SERVER_KEY] = {
    binary: { path: LSP_NPX_CMD, arguments: LSP_NPX_ARGS },
  };
  existing['lsp'] = lsp;
  await writeConfigAtomic(configPath, existing);
}

async function unconfigureZed(configPath: string): Promise<void> {
  const existing = await readConfigFile(configPath);
  const lsp = existing['lsp'] as Record<string, unknown> | undefined;
  if (lsp) {
    delete lsp[LSP_SERVER_KEY];
    if (Object.keys(lsp).length === 0) delete existing['lsp'];
    else existing['lsp'] = lsp;
  }
  await writeConfigAtomic(configPath, existing);
}

async function isZedConfigured(configPath: string): Promise<boolean> {
  try {
    const existing = await readConfigFile(configPath);
    const lsp = existing['lsp'] as Record<string, unknown> | undefined;
    return typeof lsp === 'object' && lsp !== null && LSP_SERVER_KEY in lsp;
  } catch { return false; }
}

// ── Helix: TOML append to languages.toml ────────────────────────────────────

const HELIX_MARKER = '[language-server.airtable-lsp]';

const HELIX_BLOCK = `
[language-server.airtable-lsp]
command = "npx"
args = ["-y", "airtable-user-lsp", "--stdio"]

[[language]]
name = "airtable-formula"
scope = "source.formula"
file-types = ["formula", "min.formula", "ultra-min.formula"]
language-servers = ["airtable-lsp"]

[[language]]
name = "airtable-script"
scope = "source.ats"
file-types = ["ats", "script"]
language-servers = ["airtable-lsp"]

[[language]]
name = "airtable-automation"
scope = "source.ata"
file-types = ["ata", "automation"]
language-servers = ["airtable-lsp"]
`;

async function configureHelix(configPath: string): Promise<void> {
  let existing = '';
  try { existing = await fs.promises.readFile(configPath, 'utf8'); } catch { /* new file */ }
  if (existing.includes(HELIX_MARKER)) return; // already configured
  const content = existing.trimEnd() + '\n' + HELIX_BLOCK;
  await writeTextAtomic(configPath, content);
}

async function unconfigureHelix(configPath: string): Promise<void> {
  let existing = '';
  try { existing = await fs.promises.readFile(configPath, 'utf8'); } catch { return; }
  if (!existing.includes(HELIX_MARKER)) return;
  // HELIX_BLOCK is FOUR top-level tables, not one: the language-server plus a
  // [[language]] per file type. Remove each of ours and nothing else — a
  // "delete to the next header" cut would orphan the three [[language]] blocks,
  // and the old "delete to EOF" cut destroyed the user's own config below ours.
  const next = removeTomlSections(existing, (s) => {
    if (s.header === null) return false;
    if (s.header === HELIX_MARKER) return true;
    return s.header === '[[language]]' && s.text.includes(`language-servers = ["${LSP_SERVER_KEY}"]`);
  });
  await writeTextAtomic(configPath, next);
}

async function isHelixConfigured(configPath: string): Promise<boolean> {
  try {
    const raw = await fs.promises.readFile(configPath, 'utf8');
    return raw.includes(HELIX_MARKER);
  } catch { return false; }
}

// ── Neovim: write lsp/airtable.lua ──────────────────────────────────────────

const NEOVIM_LUA = `\
-- Auto-generated by the Airtable Formula VS Code extension.
-- Add  vim.lsp.enable('airtable')  to your init.lua to activate.
return {
  cmd = { 'npx', '-y', 'airtable-user-lsp', '--stdio' },
  filetypes = { 'airtable-formula', 'airtable-script', 'airtable-automation' },
  root_markers = { '.git' },
}
`;

async function configureNeovim(configPath: string): Promise<void> {
  await writeTextAtomic(configPath, NEOVIM_LUA);
}

async function unconfigureNeovim(configPath: string): Promise<void> {
  try { await fs.promises.unlink(configPath); } catch { /* already gone */ }
}

async function isNeovimConfigured(configPath: string): Promise<boolean> {
  try { await fs.promises.access(configPath); return true; } catch { return false; }
}

// ── OpenCode: JSON merge into opencode.json (lsp key) ───────────────────────

const OPENCODE_LSP_KEY = 'airtable-formula';
const OPENCODE_LSP_ENTRY = {
  command: ['npx', '-y', 'airtable-user-lsp', '--stdio'],
  extensions: ['.formula', '.ats', '.ata'],
};

async function configureOpenCode(configPath: string): Promise<void> {
  const existing = await readConfigFile(configPath);
  const lsp = (existing['lsp'] ?? {}) as Record<string, unknown>;
  lsp[OPENCODE_LSP_KEY] = OPENCODE_LSP_ENTRY;
  existing['lsp'] = lsp;
  await writeConfigAtomic(configPath, existing);
}

async function unconfigureOpenCode(configPath: string): Promise<void> {
  const existing = await readConfigFile(configPath);
  const lsp = existing['lsp'] as Record<string, unknown> | undefined;
  if (lsp) {
    delete lsp[OPENCODE_LSP_KEY];
    if (Object.keys(lsp).length === 0) delete existing['lsp'];
    else existing['lsp'] = lsp;
  }
  await writeConfigAtomic(configPath, existing);
}

async function isOpenCodeLspConfigured(configPath: string): Promise<boolean> {
  try {
    const existing = await readConfigFile(configPath);
    const lsp = existing['lsp'] as Record<string, unknown> | undefined;
    return typeof lsp === 'object' && lsp !== null && OPENCODE_LSP_KEY in lsp;
  } catch { return false; }
}

// ── Codex CLI: TOML append to config.toml ────────────────────────────────────

const CODEX_MARKER = '[mcp_servers.airtable-user-mcp]';

const CODEX_BLOCK = `
[mcp_servers.airtable-user-mcp]
type = "stdio"
command = "npx"
args = ["-y", "airtable-user-mcp"]
`;

export async function configureMcpToml(configPath: string): Promise<void> {
  let existing = '';
  try { existing = await fs.promises.readFile(configPath, 'utf8'); } catch { /* new file */ }
  if (existing.includes(CODEX_MARKER)) return;
  const content = existing.trimEnd() + '\n' + CODEX_BLOCK;
  await writeTextAtomic(configPath, content);
}

export async function unconfigureMcpToml(configPath: string): Promise<void> {
  let existing = '';
  try { existing = await fs.promises.readFile(configPath, 'utf8'); } catch { return; }
  if (!existing.includes(CODEX_MARKER)) return;
  // Remove only our own table. This used to truncate the file from the marker to
  // EOF — and since both `configureMcpToml` and `codex mcp add` append at EOF,
  // any MCP server or [model_providers.*] block the user added after Setup sat
  // below ours and was silently destroyed by clicking Unconfigure.
  const next = removeTomlSections(existing, (s) => s.header === CODEX_MARKER);
  await writeTextAtomic(configPath, next);
}

export async function isMcpTomlConfigured(configPath: string): Promise<boolean> {
  try {
    const raw = await fs.promises.readFile(configPath, 'utf8');
    return raw.includes(CODEX_MARKER);
  } catch { return false; }
}

// ── Shared TOML section surgery ─────────────────────────────────────────────

/**
 * A complete top-level TOML table header on its own line: `[table]`, `[[array]]`,
 * optionally dotted/quoted, optionally trailing comment.
 *
 * Deliberately strict. A loose `/^\s*\[/` also matches a continuation line of a
 * multi-line array (`matrix = [\n[1,2],\n]`), which would split a user's value in
 * half and corrupt the file — the exact class of bug this helper exists to fix.
 */
const TOML_HEADER_RE = /^[ \t]*\[\[?[A-Za-z0-9_.\-"' ]+\]\]?[ \t]*(?:#.*)?$/;

interface TomlSection { header: string | null; text: string }

/** Split a TOML document into a preamble plus one entry per top-level header. */
function splitTomlSections(text: string): TomlSection[] {
  const sections: TomlSection[] = [];
  let current: TomlSection = { header: null, text: '' };
  for (const line of text.split('\n')) {
    if (TOML_HEADER_RE.test(line)) {
      sections.push(current);
      current = { header: line.trim(), text: line + '\n' };
    } else {
      current.text += line + '\n';
    }
  }
  sections.push(current);
  return sections.filter((s, i) => i === 0 || s.header !== null);
}

/**
 * Drop only the sections we own, preserving everything else verbatim.
 *
 * The previous implementation did `existing.slice(0, indexOf(MARKER))` — i.e. it
 * truncated the user's file from our marker to EOF, destroying any config that
 * happened to sit below ours. Since `configureMcpToml` appends at EOF and
 * `codex mcp add` does too, a second MCP server added after Setup was silently
 * deleted by clicking Unconfigure.
 */
function removeTomlSections(text: string, isOurs: (s: TomlSection) => boolean): string {
  const kept = splitTomlSections(text).filter((s) => !isOurs(s));
  const out = kept.map((s) => s.text).join('').replace(/\n{3,}/g, '\n\n').trimEnd();
  return out === '' ? '' : out + '\n';
}

// ── Shared text-file atomic writer ──────────────────────────────────────────

async function writeTextAtomic(filePath: string, content: string): Promise<void> {
  const tmp = `${filePath}.${crypto.randomBytes(6).toString('hex')}.tmp`;
  await fs.promises.mkdir(path.dirname(filePath), { recursive: true });
  try {
    await fs.promises.writeFile(tmp, content, 'utf8');
    await fs.promises.rename(tmp, filePath);
  } catch (err) {
    await fs.promises.unlink(tmp).catch(() => {});
    throw err;
  }
}

// ── Public API ──────────────────────────────────────────────────────────────

export async function configureLspForIde(ideId: IdeId): Promise<void> {
  const cfg = IDE_CONFIGS[ideId];
  if (!cfg.lspConfigPath || !cfg.lspConfigFormat) return;
  switch (cfg.lspConfigFormat) {
    case 'json-merge':
      return ideId === 'opencode' ? configureOpenCode(cfg.lspConfigPath) : configureZed(cfg.lspConfigPath);
    case 'toml-append':  return configureHelix(cfg.lspConfigPath);
    case 'lua-write':    return configureNeovim(cfg.lspConfigPath);
  }
}

export async function unconfigureLspForIde(ideId: IdeId): Promise<void> {
  const cfg = IDE_CONFIGS[ideId];
  if (!cfg.lspConfigPath || !cfg.lspConfigFormat) return;
  switch (cfg.lspConfigFormat) {
    case 'json-merge':
      return ideId === 'opencode' ? unconfigureOpenCode(cfg.lspConfigPath) : unconfigureZed(cfg.lspConfigPath);
    case 'toml-append':  return unconfigureHelix(cfg.lspConfigPath);
    case 'lua-write':    return unconfigureNeovim(cfg.lspConfigPath);
  }
}

export async function isLspConfigured(ideId: IdeId): Promise<boolean> {
  const cfg = IDE_CONFIGS[ideId];
  if (!cfg.lspConfigPath || !cfg.lspConfigFormat) return false;
  switch (cfg.lspConfigFormat) {
    case 'json-merge':
      return ideId === 'opencode' ? isOpenCodeLspConfigured(cfg.lspConfigPath) : isZedConfigured(cfg.lspConfigPath);
    case 'toml-append':  return isHelixConfigured(cfg.lspConfigPath);
    case 'lua-write':    return isNeovimConfigured(cfg.lspConfigPath);
  }
}
