import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';
import type { IdeId } from '@airtable-formula/shared';
import { IDE_CONFIGS } from './ide-configs.js';
import { readConfigFile, writeConfigAtomic } from './ide-detection.js';

const LSP_SERVER_KEY = 'airtable-lsp';
const LSP_NPX_CMD   = 'npx';
const LSP_NPX_ARGS  = ['-y', 'airtable-user-lsp', '--stdio'];

// ── Zed: JSON merge into settings.json ─────────────────────────────────────

async function configureZed(configPath: string): Promise<void> {
  const existing = await readConfigFile(configPath);
  const lsp = (existing['lsp'] ?? {}) as Record<string, unknown>;
  lsp[LSP_SERVER_KEY] = {
    binary: { path: LSP_NPX_CMD, arguments: LSP_NPX_ARGS },
  };
  existing['lsp'] = lsp;
  await writeConfigAtomic(configPath, existing);
}

async function unconfigureZed(configPath: string): Promise<void> {
  const existing = await readConfigFile(configPath);
  const lsp = existing['lsp'] as Record<string, unknown> | undefined;
  if (lsp) {
    delete lsp[LSP_SERVER_KEY];
    if (Object.keys(lsp).length === 0) delete existing['lsp'];
    else existing['lsp'] = lsp;
  }
  await writeConfigAtomic(configPath, existing);
}

async function isZedConfigured(configPath: string): Promise<boolean> {
  try {
    const existing = await readConfigFile(configPath);
    const lsp = existing['lsp'] as Record<string, unknown> | undefined;
    return typeof lsp === 'object' && lsp !== null && LSP_SERVER_KEY in lsp;
  } catch { return false; }
}

// ── Helix: TOML append to languages.toml ────────────────────────────────────

const HELIX_MARKER = '[language-server.airtable-lsp]';

const HELIX_BLOCK = `
[language-server.airtable-lsp]
command = "npx"
args = ["-y", "airtable-user-lsp", "--stdio"]

[[language]]
name = "airtable-formula"
scope = "source.formula"
file-types = ["formula", "min.formula", "ultra-min.formula"]
language-servers = ["airtable-lsp"]

[[language]]
name = "airtable-script"
scope = "source.ats"
file-types = ["ats", "script"]
language-servers = ["airtable-lsp"]

[[language]]
name = "airtable-automation"
scope = "source.ata"
file-types = ["ata", "automation"]
language-servers = ["airtable-lsp"]
`;

async function configureHelix(configPath: string): Promise<void> {
  let existing = '';
  try { existing = await fs.promises.readFile(configPath, 'utf8'); } catch { /* new file */ }
  if (existing.includes(HELIX_MARKER)) return; // already configured
  const content = existing.trimEnd() + '\n' + HELIX_BLOCK;
  await writeTextAtomic(configPath, content);
}

async function unconfigureHelix(configPath: string): Promise<void> {
  let existing = '';
  try { existing = await fs.promises.readFile(configPath, 'utf8'); } catch { return; }
  if (!existing.includes(HELIX_MARKER)) return;
  // Remove everything from HELIX_MARKER to the next blank-line-separated section
  const idx = existing.indexOf(HELIX_MARKER);
  const before = existing.slice(0, idx).trimEnd();
  await writeTextAtomic(configPath, before + '\n');
}

async function isHelixConfigured(configPath: string): Promise<boolean> {
  try {
    const raw = await fs.promises.readFile(configPath, 'utf8');
    return raw.includes(HELIX_MARKER);
  } catch { return false; }
}

// ── Neovim: write lsp/airtable.lua ──────────────────────────────────────────

const NEOVIM_LUA = `\
-- Auto-generated by the Airtable Formula VS Code extension.
-- Add  vim.lsp.enable('airtable')  to your init.lua to activate.
return {
  cmd = { 'npx', '-y', 'airtable-user-lsp', '--stdio' },
  filetypes = { 'airtable-formula', 'airtable-script', 'airtable-automation' },
  root_markers = { '.git' },
}
`;

async function configureNeovim(configPath: string): Promise<void> {
  await writeTextAtomic(configPath, NEOVIM_LUA);
}

async function unconfigureNeovim(configPath: string): Promise<void> {
  try { await fs.promises.unlink(configPath); } catch { /* already gone */ }
}

async function isNeovimConfigured(configPath: string): Promise<boolean> {
  try { await fs.promises.access(configPath); return true; } catch { return false; }
}

// ── Codex CLI: TOML append to config.toml ────────────────────────────────────

const CODEX_MARKER = '[mcp_servers.airtable-user-mcp]';

const CODEX_BLOCK = `
[mcp_servers.airtable-user-mcp]
type = "stdio"
command = "npx"
args = ["-y", "airtable-user-mcp"]
`;

export async function configureMcpToml(configPath: string): Promise<void> {
  let existing = '';
  try { existing = await fs.promises.readFile(configPath, 'utf8'); } catch { /* new file */ }
  if (existing.includes(CODEX_MARKER)) return;
  const content = existing.trimEnd() + '\n' + CODEX_BLOCK;
  await writeTextAtomic(configPath, content);
}

export async function unconfigureMcpToml(configPath: string): Promise<void> {
  let existing = '';
  try { existing = await fs.promises.readFile(configPath, 'utf8'); } catch { return; }
  if (!existing.includes(CODEX_MARKER)) return;
  const idx = existing.indexOf(CODEX_MARKER);
  const before = existing.slice(0, idx).trimEnd();
  await writeTextAtomic(configPath, before + '\n');
}

export async function isMcpTomlConfigured(configPath: string): Promise<boolean> {
  try {
    const raw = await fs.promises.readFile(configPath, 'utf8');
    return raw.includes(CODEX_MARKER);
  } catch { return false; }
}

// ── Shared text-file atomic writer ──────────────────────────────────────────

async function writeTextAtomic(filePath: string, content: string): Promise<void> {
  const tmp = `${filePath}.${crypto.randomBytes(6).toString('hex')}.tmp`;
  await fs.promises.mkdir(path.dirname(filePath), { recursive: true });
  try {
    await fs.promises.writeFile(tmp, content, 'utf8');
    await fs.promises.rename(tmp, filePath);
  } catch (err) {
    await fs.promises.unlink(tmp).catch(() => {});
    throw err;
  }
}

// ── Public API ──────────────────────────────────────────────────────────────

export async function configureLspForIde(ideId: IdeId): Promise<void> {
  const cfg = IDE_CONFIGS[ideId];
  if (!cfg.lspConfigPath || !cfg.lspConfigFormat) return;
  switch (cfg.lspConfigFormat) {
    case 'json-merge':   return configureZed(cfg.lspConfigPath);
    case 'toml-append':  return configureHelix(cfg.lspConfigPath);
    case 'lua-write':    return configureNeovim(cfg.lspConfigPath);
  }
}

export async function unconfigureLspForIde(ideId: IdeId): Promise<void> {
  const cfg = IDE_CONFIGS[ideId];
  if (!cfg.lspConfigPath || !cfg.lspConfigFormat) return;
  switch (cfg.lspConfigFormat) {
    case 'json-merge':   return unconfigureZed(cfg.lspConfigPath);
    case 'toml-append':  return unconfigureHelix(cfg.lspConfigPath);
    case 'lua-write':    return unconfigureNeovim(cfg.lspConfigPath);
  }
}

export async function isLspConfigured(ideId: IdeId): Promise<boolean> {
  const cfg = IDE_CONFIGS[ideId];
  if (!cfg.lspConfigPath || !cfg.lspConfigFormat) return false;
  switch (cfg.lspConfigFormat) {
    case 'json-merge':   return isZedConfigured(cfg.lspConfigPath);
    case 'toml-append':  return isHelixConfigured(cfg.lspConfigPath);
    case 'lua-write':    return isNeovimConfigured(cfg.lspConfigPath);
  }
}
